---
abstract: 'Rapid (and easy!) creation of command line applications'
author:
  - 'Breno G. de Oliveira <garu at cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6501, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Rad
no_index:
  directory:
    - t
    - inc
requires:
  Attribute::Handlers: 0
  B::Deparse: 0
  Carp: 0
  File::Temp: 0
  FindBin: 0
  Getopt::Long: 2.36
  Test::More: 0
version: 1.05
