--- #YAML:1.0
name:               App-Rad
version:            0.7
abstract:           Rapid (and easy!) creation of command line applications
author:
    - Breno G. de Oliveira <garu at cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    File::Temp:    0
    Getopt::Long:  2.36
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
