--- #YAML:1.0
name:                App-Rad
version:             0.5
abstract:            Rapid (and easy!) creation of command line applications
license:             ~
author:              
    - Breno G. de Oliveira <garu at cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    File::Temp:                    0
    Getopt::Long:                  2.36
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
